### ISSUE TITLE
Wrong type for list allowed apis accessLevels response

### ISSUE THREAD

**Issue by manuelmazzuola** [akamai/akamai-apis#12]
The schema defines the allowed api accessLevels as a string https://github.com/akamai/akamai-apis/blob/6d0c818a076393c205eda045bcbfe68f08f523ff/apis/identity-management/v3/schemas/AllowedApisResponse.yaml#L27  

It should be an array of strings as described here https://techdocs.akamai.com/iam-api/reference/get-api-clients-users-allowed-apis

### Issue type

- [x] Bug
- [ ] New feature request
- [ ] Improvement
- [ ] Documentation (description, summaries, general text field issues)

### Which API?
V3
List allowed apis for a user

**Comment by skearney-akamai** [comment]
Hello. Thank you for catching this. We're looking into it and will get back to you when we have some information for you.

**Comment by skearney-akamai** [comment]
Internal note: IDM-3344 created to update the schema.

**Comment by skearney-akamai** [comment]
Hello. A recent update of the Identity Management API schema has corrected this issue. See https://github.com/akamai/akamai-apis/blob/main/apis/identity-management/v3/schemas/allowed-apis-response.yaml#L27. 

Thank you. I'll close this issue with this comment, but if this fix doesn't work for you, please let me know.
