### ISSUE TITLE
Bot Manager Specs

### ISSUE THREAD

**Issue by timoguin** [akamai/akamai-apis#14]
Bot Manager is a part of Application Security, but there are no references at all to its endpoints in these OpenAPI specs.

The Akamai Go SDK, however, has a separate package called `botman` that is also utilized by the Terraform provider.

It would be great if we could get OpenAPI specs for these resources.

## References

- `GetAkamaiBotCategoryList` function from Go SDK: https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/master/pkg/botman/akamai_bot_category.go#L31
- Botman section of Terraform docs: https://techdocs.akamai.com/terraform/docs/set-up-botman

**Comment by skearney-akamai** [comment]
@timoguin, 

Those endpoints are limited-audience and can’t be published here. While the other locations you've pointed out do have information, it’s controlled information. 

If your contract includes Bot Manager, access its product documentation through Control Center. From there, click on the API tab at the top and you’ll have access to the API spec. 

Closing.
