### ISSUE TITLE
Typo in the Python Invalidate content by URL or ARL Recipe

### ISSUE THREAD

**Issue by phillipsj** [akamai/akamai-apis#5]
### Issue type

- [ ] Bug
- [ ] New feature request
- [ ] Improvement
- [X] Documentation (description, summaries, general text field issues)

### Which API?

CCUV3

### Issue

The Python recipe for the Invalidate Content by URL or ARL references in the current API endpoint. It has tag when it should be URL.

### Context

Incorrect sample was a little confusing, luckily I was able to catch it before doing testing.

### Bugs: Steps to reproduce
 Navigate to https://techdocs.akamai.com/purge-cache/recipes/invalidate-content-by-url-or-arl and click on the Python tab. Noticed that on line 13, that tag is reference not URL.

### Possible solution

Update the documentation.

**Comment by skearney-akamai** [comment]
Thank you for letting us know about the issue. 

It's been updated. 

Closing the issue as fixed.
